### ISSUE TITLE
Add myself Nicolas Bovard to the list of students

### ISSUE THREAD

**Issue by nicolasbvd** [heig-vd-dai-course/.github#104]
I would like to add myself to the list of students in the GitHub organization README.

**Comment by ludelafo** [comment]
It seems everything is OK but you have forgot to create the PR as mentioned in the course material to ask us to merge your work: https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#create-a-pull-request.
