### ISSUE TITLE
Add myself (Jonathan Thiebaud) to the list of students

### ISSUE THREAD

**Issue by JONATHAN-THIEBAUD** [heig-vd-dai-course/.github#152]
I would like to add myself to the list of students in the GitHub organization README.

**Comment by ludelafo** [comment]
I have opened the issue again as the PR associated it not done yet. :) Please check my comments on the PR.

**Comment by JONATHAN-THIEBAUD** [comment]
I added myself to the right file now !

**Comment by ludelafo** [comment]
I don't see the changes, have you pushed them on your repository?

**Comment by JONATHAN-THIEBAUD** [comment]
yes i think that everything is up to date

**Comment by ludelafo** [comment]
Could you send me the link? I'm not able to find the changes.

**Comment by JONATHAN-THIEBAUD** [comment]
I added mysef into this README.md file : https://github.com/heig-vd-dai-course/.github/tree/main/profile/README.md

And i commited the changes.

**Comment by ludelafo** [comment]
Would you be available for a Teams call now or tomorrow? I still don't see your name and I would like to be sure you have everything needed to succeed.

**Comment by JONATHAN-THIEBAUD** [comment]
Yes ofc thanks a lot. I added my name but when i refresh the page, i'm not able to see my name as well. If you don't know why we can have a call
![Capture d'écran 2024-09-25 180717](https://github.com/user-attachments/assets/fe3ffa2d-2284-4c73-9d0c-d5b75fcdc85a)
