### ISSUE TITLE
Add myself (Romain Holzer) to the list of students

### ISSUE THREAD

**Issue by Romain1109** [heig-vd-dai-course/.github#190]
I would like to add myself to the list of students in the GitHub organization README

**Comment by ludelafo** [comment]
I haven't seen any PR yet for you based on the course material (https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#add-yourself-to-the-list-of-students-in-the-github-organization), is everything fine on your side?
